---
- name: Install docker
  apt:
    pkg:
      - docker.io
    state: present

- name: Install docker-compose
  apt:
    pkg:
      -  docker-compose
    state: present

- name: Copy files
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    -  { src: .env, dest: /root/.env }
    -  { src: docker-compose.yml, dest: /root/docker-compose.yml }
    -  { src: dockerfile, dest: /root/dockerfile }
    -  { src: HelloWorldApp.py, dest: /root/HelloWorldApp.py}
